name: Electron CD

on:
  push:
    branches:
      - master
  schedule:
    - cron: '42 0 9 1 *'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarn install
        run: |
          yarn install
      - name: Publish
        env:
          USE_HARD_LINKS: "false"
        run: |
          yarn electron:build
      - name: Cleanup artifacts macOS
        if: matrix.os == 'macOS-latest'
        run: |
          mkdir artifacts
          mv dist_electron/*.dmg artifacts || true
      - name: Cleanup artifacts ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir artifacts
          mv dist_electron/*.AppImage artifacts || true
      - name: Cleanup artifacts Windows
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifacts
          mv dist_electron/*.exe artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.os}}
          path: artifacts
